# Generated by Django 3.1.3 on 2020-11-30 02:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('age', models.IntegerField(default=20)),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
